--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2023-10-13 19:50:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16417)
-- Name: uhistory_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uhistory_logs (
    id_log integer NOT NULL,
    user_id integer NOT NULL,
    time_stamp timestamp without time zone DEFAULT now() NOT NULL,
    activity_type character varying(255) NOT NULL
);


ALTER TABLE public.uhistory_logs OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16423)
-- Name: uhistory_logs_id_log_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.uhistory_logs ALTER COLUMN id_log ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uhistory_logs_id_log_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16405)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id_user integer NOT NULL,
    surname character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    age integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16424)
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4790 (class 0 OID 16417)
-- Dependencies: 216
-- Data for Name: uhistory_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.uhistory_logs (id_log, user_id, time_stamp, activity_type) FROM stdin;
4	10	2023-10-13 16:57:12.202814	create
5	10	2023-10-13 16:58:28.053834	update
6	10	2023-10-13 18:11:51.699339	update
7	10	2023-10-13 18:11:54.556656	update
8	10	2023-10-13 18:11:56.771584	update
9	10	2023-10-13 18:11:59.863041	update
10	10	2023-10-13 18:12:02.042945	update
11	10	2023-10-13 18:12:04.776502	update
12	10	2023-10-13 18:12:22.9383	update
13	10	2023-10-13 18:12:25.362628	update
14	10	2023-10-13 18:12:27.639704	update
15	10	2023-10-13 18:12:29.718277	update
16	10	2023-10-13 18:12:31.519298	update
17	10	2023-10-13 18:15:00.009731	update
18	10	2023-10-13 18:15:34.700416	update
\.


--
-- TOC entry 4789 (class 0 OID 16405)
-- Dependencies: 215
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id_user, surname, city, age, name) FROM stdin;
1	Sanches-Peres	msk	110	Sergey
3	Petrov	msk	20	Ivan
4	Petrova	msk	21	Ekaterina
5	Romanov	msk	28	Leonid
2	Ivanov	spb	22	Alexei
6	Nesterov	spb	18	Eugene
7	Lomonosov	spb	32	Vasily
8	Popova	spb	25	Liza
9	Test	spb	25	TestUser
10	Rish555556ddd	msk	22	Nikolaifdf437gggfff
\.


--
-- TOC entry 4798 (class 0 OID 0)
-- Dependencies: 217
-- Name: uhistory_logs_id_log_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.uhistory_logs_id_log_seq', 18, true);


--
-- TOC entry 4799 (class 0 OID 0)
-- Dependencies: 218
-- Name: users_id_user_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_user_seq', 10, true);


--
-- TOC entry 4643 (class 2606 OID 16421)
-- Name: uhistory_logs uh_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uhistory_logs
    ADD CONSTRAINT uh_logs_pkey PRIMARY KEY (id_log);


--
-- TOC entry 4641 (class 2606 OID 16411)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- TOC entry 4644 (class 1259 OID 16425)
-- Name: uhistory_logs_user_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uhistory_logs_user_id_idx ON public.uhistory_logs USING btree (user_id) WITH (deduplicate_items='true');


--
-- TOC entry 4645 (class 2606 OID 16427)
-- Name: uhistory_logs uhistory_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uhistory_logs
    ADD CONSTRAINT uhistory_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id_user) NOT VALID;


-- Completed on 2023-10-13 19:50:07

--
-- PostgreSQL database dump complete
--

