--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0
-- Dumped by pg_dump version 16.0

-- Started on 2023-10-13 02:45:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16412)
-- Name: uhistory_activity_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uhistory_activity_types (
    id_activity integer NOT NULL,
    title character varying(255) NOT NULL
);


ALTER TABLE public.uhistory_activity_types OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16422)
-- Name: uhistory_activity_types_id_activity_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.uhistory_activity_types ALTER COLUMN id_activity ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uhistory_activity_types_id_activity_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16417)
-- Name: uhistory_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.uhistory_logs (
    id_log integer NOT NULL,
    user_id integer NOT NULL,
    activity_type_id integer NOT NULL,
    time_stamp timestamp without time zone
);


ALTER TABLE public.uhistory_logs OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16423)
-- Name: uhistory_logs_id_log_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.uhistory_logs ALTER COLUMN id_log ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uhistory_logs_id_log_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16405)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id_user integer NOT NULL,
    surname character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    age integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16424)
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4798 (class 0 OID 16412)
-- Dependencies: 216
-- Data for Name: uhistory_activity_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.uhistory_activity_types (id_activity, title) FROM stdin;
\.


--
-- TOC entry 4799 (class 0 OID 16417)
-- Dependencies: 217
-- Data for Name: uhistory_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.uhistory_logs (id_log, user_id, activity_type_id, time_stamp) FROM stdin;
\.


--
-- TOC entry 4797 (class 0 OID 16405)
-- Dependencies: 215
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id_user, surname, city, age, name) FROM stdin;
1	Sanches-Peres	msk	110	Sergey
2	Ivanov	spb	20	Roman
3	Petrov	msk	20	Ivan
4	Petrova	msk	21	Ekaterina
5	Romanov	msk	28	Leonid
\.


--
-- TOC entry 4808 (class 0 OID 0)
-- Dependencies: 218
-- Name: uhistory_activity_types_id_activity_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.uhistory_activity_types_id_activity_seq', 1, false);


--
-- TOC entry 4809 (class 0 OID 0)
-- Dependencies: 219
-- Name: uhistory_logs_id_log_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.uhistory_logs_id_log_seq', 1, false);


--
-- TOC entry 4810 (class 0 OID 0)
-- Dependencies: 220
-- Name: users_id_user_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_user_seq', 5, true);


--
-- TOC entry 4647 (class 2606 OID 16416)
-- Name: uhistory_activity_types activity_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uhistory_activity_types
    ADD CONSTRAINT activity_type_pkey PRIMARY KEY (id_activity);


--
-- TOC entry 4649 (class 2606 OID 16421)
-- Name: uhistory_logs uh_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uhistory_logs
    ADD CONSTRAINT uh_logs_pkey PRIMARY KEY (id_log);


--
-- TOC entry 4645 (class 2606 OID 16411)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- TOC entry 4650 (class 1259 OID 16426)
-- Name: uhistory_logs_activity_type_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uhistory_logs_activity_type_id_idx ON public.uhistory_logs USING btree (activity_type_id) WITH (deduplicate_items='true');


--
-- TOC entry 4651 (class 1259 OID 16425)
-- Name: uhistory_logs_user_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX uhistory_logs_user_id_idx ON public.uhistory_logs USING btree (user_id) WITH (deduplicate_items='true');


--
-- TOC entry 4652 (class 2606 OID 16432)
-- Name: uhistory_logs uhistory_logs_activity_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uhistory_logs
    ADD CONSTRAINT uhistory_logs_activity_type_id_fkey FOREIGN KEY (activity_type_id) REFERENCES public.uhistory_activity_types(id_activity) NOT VALID;


--
-- TOC entry 4653 (class 2606 OID 16427)
-- Name: uhistory_logs uhistory_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.uhistory_logs
    ADD CONSTRAINT uhistory_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id_user) NOT VALID;


-- Completed on 2023-10-13 02:45:31

--
-- PostgreSQL database dump complete
--

